name: "pr-size-labeler"
description: "Label a PR using its pr-size-labeler"
inputs: 
  GITHUB_TOKEN:
    description: "GitHub Token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.GITHUB_TOKEN }}