name: "pr-size-labeler"
description: "Label a PR using its pr-size-labeler"
inputs: 
  github_token:
    description: "GitHub Token"
    required: true
  xs_max_size:
    description: "Max size for a PR to be considered xs"
    required: false
    default: "10"
  s_max_size:
    description: "Max size for a PR to be considered s"
    required: false
    default: "100"
  m_max_size:
    description: "Max size for a PR to be considered m"
    required: false
    default: "500"
  l_max_size:
    description: "Max size for a PR to be considered l"
    required: false
    default: "1000"
  fail_if_xl:
    description: "Fail if a PR is of xl size"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.xs_max_size }}
    - ${{ inputs.s_max_size }}
    - ${{ inputs.m_max_size }}
    - ${{ inputs.l_max_size }}
    - ${{ inputs.fail_if_xl }}